pipeline {

    agent any

    stages {
        stage('Delete previous version') {
            steps {
                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: 'NGINX_VM', 
                            transfers: [
                                sshTransfer(
                                    execCommand: 'sudo rm -r -f /var/www/market'
                                )
                            ]
                        )
                    ]
                )
            }
        }
        stage("Recover artifacts from build pipeline") {
            steps {
                copyArtifacts(
                    projectName: "market_frontend_ssh_build",
                    selector: upstream(),
                    filter: "build/**"
                )
            }
        }
        stage('Copy live version to NGINX vm server') {
            steps {
                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: 'NGINX_VM', 
                            transfers: [
                                sshTransfer(
                                    //execCommand: '''cd && ./ngrok http 80''',
                                    execCommand: 'sudo mv market/ /var/www/',
                                    makeEmptyDirs: false,
                                    remoteDirectory: 'market',
                                    removePrefix: 'build', 
                                    sourceFiles: 'build/**'
                                )
                            ]
                        )
                    ]
                )
            }
        }
    }
    post {
        success {
            echo "All done."
            echo "Live version has been deployed."
        }
    }
}